[package]
name = "rylr-tokio"
version.workspace = true
edition.workspace = true

[dependencies]
rylr-core    = { workspace = true, features = ["alloc", "std"] }
tokio        = { workspace = true, features = ["rt", "io-util", "sync", "macros", "time"] }
tokio-serial = { workspace = true }
thiserror    = { workspace = true }
